http:
  middlewares:
    cache:
      advancedCache:
        configPath: "advancedCache.cfg.yaml"

  routers:
    proxy-router:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: upstream
      middlewares:
        - cache

  services:
    upstream:
      loadBalancer:
        servers:
          - url: "http://seo-master-seo:8080"
