cache:
  env: "dev"
  enabled: true

  logs:
    level: "info" # Any zerolog.Level.
    stats: true   # Should the statistic like num evictions, refreshes, rps, memory usage and so on be written in /std/out?

  forceGC:
    enabled: true
    interval: "10s"

  lifetime:
    maxReqDur: "100ms"                # If a request lifetime is longer than 100ms then request will be canceled by context.
    escapeMaxReqDur: "X-Google-Bot"  # If the header exists the timeout above will be skipped.

  upstream:
    url: "http://localhost:8021" # downstream reverse proxy host:port
    rate: 8000000                                    # Rate limiting reqs to backend per second.
    timeout: "10s"                              # Timeout for requests to backend.

  preallocate:
    numShards: 2048  # Fixed constant (see `NumOfShards` in code). Controls the number of sharded maps.
    perShard: 256    # Preallocated map size per shard. Without resizing, this supports 2048*8196=~16785408 keys in total.
    # Note: this is an upper-bound estimate and may vary depending on hash distribution quality.

  eviction:
    threshold: 0.9    # Trigger eviction when cache memory usage exceeds 90% of its configured limit.

  storage:
    size: 34359738368 # 32GB of maximum allowed memory for the in-memory cache (in bytes).

  refresh:
    enabled: true
    ttl: "12h"
    errorTTL: "3h"
    rate: 80               # Rate limiting reqs to backend per second.
    scanRate: 10000       # Rate limiting of num scans items per second.
    beta: 0.4              # Controls randomness in refresh timing to avoid thundering herd (from 0 to 1).

  persistence:
    dump:
      enabled: true
      dumpDir: "public/dump"     # dump dir.
      dumpName: "cache.dump.gz"  # dump name
      maxVersions: 3

  rules:
    /api/v2/pagedata:
      gzip:
        enabled: false
        threshold: 1024
      ttl: "20m"
      errorTTL: "5m"
      beta: 0.3 # Controls randomness in refresh timing to avoid thundering herd.
      cacheKey:
        query: ['project[id]', 'domain', 'language', 'choice'] # Match query parameters by prefix.
        headers:
          - Accept-Encoding
      cacheValue:
        headers:
          - Content-Type
          - Content-Encoding
          - Cache-Control
          - Vary
          - Strict-Transport-Security
          - Content-Length
          - Cache-Control
          - X-Content-Digest
          - Age

    /api/v1/pagecontent:
      gzip:
        enabled: true
        threshold: 1024
      ttl: "36h"
      errorTTL: "3h"
      beta: 0.3 # Controls randomness in refresh timing to avoid thundering herd.
      cacheKey:
        query: ['project[id]', 'domain', 'language', 'choice'] # Match query parameters by prefix.
        headers: ['Accept-Encoding', 'X-Project-ID']           # Match headers by exact value.
      cacheValue:
        headers: ['X-Project-ID']                              # Store only when headers match exactly.
